class Field:
    install_fields = "blocked_reason_rule,store_reinstall,impressions,contributor3_match_type,custom_dimension,conversion_type,gp_click_time,match_type,mediation_network,oaid,deeplink_url,blocked_reason,blocked_sub_reason,gp_broadcast_referrer,gp_install_begin,campaign_type,custom_data,rejected_reason,device_download_time,keyword_match_type,contributor1_match_type,contributor2_match_type,device_model,monetization_network,segment,is_lat,gp_referrer,blocked_reason_value,store_product_page,device_category,app_type,rejected_reason_value,ad_unit,keyword_id,placement,network_account_id,install_app_store,amazon_aid,att"
    in_app_events_fields = "blocked_reason_rule,store_reinstall,impressions,contributor3_match_type,custom_dimension,conversion_type,gp_click_time,match_type,mediation_network,oaid,deeplink_url,blocked_reason,blocked_sub_reason,gp_broadcast_referrer,gp_install_begin,campaign_type,custom_data,rejected_reason,device_download_time,keyword_match_type,contributor1_match_type,contributor2_match_type,device_model,monetization_network,segment,is_lat,gp_referrer,blocked_reason_value,store_product_page,device_category,app_type,rejected_reason_value,ad_unit,keyword_id,placement,network_account_id,install_app_store,amazon_aid,att"
    uninstall_fields = "blocked_reason_rule,store_reinstall,impressions,contributor3_match_type,gp_click_time,match_type,mediation_network,oaid,deeplink_url,blocked_reason,blocked_sub_reason,gp_broadcast_referrer,gp_install_begin,custom_data,rejected_reason,device_download_time,keyword_match_type,contributor1_match_type,contributor2_match_type,device_model,monetization_network,segment,is_lat,gp_referrer,blocked_reason_value,device_category,rejected_reason_value,ad_unit,keyword_id,placement,network_account_id,install_app_store,amazon_aid"
    organic_install_fields = "blocked_reason_rule,store_reinstall,impressions,contributor3_match_type,custom_dimension,conversion_type,gp_click_time,match_type,mediation_network,oaid,deeplink_url,blocked_reason,blocked_sub_reason,gp_broadcast_referrer,gp_install_begin,campaign_type,custom_data,rejected_reason,device_download_time,keyword_match_type,contributor1_match_type,contributor2_match_type,device_model,monetization_network,segment,is_lat,gp_referrer,blocked_reason_value,device_category,app_type,rejected_reason_value,ad_unit,keyword_id,placement,network_account_id,install_app_store,amazon_aid,att"
    organic_in_app_events_fields = "blocked_reason_rule,store_reinstall,impressions,contributor3_match_type,custom_dimension,conversion_type,gp_click_time,match_type,mediation_network,oaid,deeplink_url,blocked_reason,blocked_sub_reason,gp_broadcast_referrer,gp_install_begin,campaign_type,custom_data,rejected_reason,device_download_time,keyword_match_type,contributor1_match_type,contributor2_match_type,device_model,monetization_network,segment,gp_referrer,blocked_reason_value,device_category,app_type,rejected_reason_value,ad_unit,keyword_id,placement,network_account_id,install_app_store,amazon_aid,att"
    organic_uninstall_fields = "blocked_reason_rule,store_reinstall,impressions,contributor3_match_type,gp_click_time,match_type,mediation_network,oaid,deeplink_url,blocked_reason,blocked_sub_reason,gp_broadcast_referrer,gp_install_begin,custom_data,rejected_reason,device_download_time,keyword_match_type,contributor1_match_type,contributor2_match_type,device_model,monetization_network,segment,is_lat,gp_referrer,blocked_reason_value,device_category,rejected_reason_value,ad_unit,keyword_id,placement,network_account_id,install_app_store,amazon_aid"


class Report:
    reports = {
        "installs_report": Field.install_fields,
        "in_app_events_report": Field.in_app_events_fields,
        "uninstall_events_report": Field.uninstall_fields,
        "organic_installs_report": Field.organic_install_fields,
        "organic_in_app_events_report": Field.organic_in_app_events_fields,
        "organic_uninstall_events_report": Field.uninstall_fields,
    }

class AppsflyerFields:
    install_fields = [
        'Event Revenue Currency',
        'Cost Model',
        'Cost Value',
        'Cost Currency',
        'Partner',
        "Campaign Type",
        "Event Time",
        "Event Name",
        "Media Source",
        "Channel",
        "Campaign",
        "Adset",
        "Adset ID",
        "Country Code",
        "State",
        "City",
        "IP",
        "Operator",
        "Carrier",
        "AppsFlyer ID",
        "Advertising ID",
        "IDFA",
        "Android ID",
        "IMEI",
        "IDFV",
        "OS Version",
        "Device Model",
        "Device Category",
        "Contributor 1 Partner",
        "Contributor 1 Media Source",
        "Contributor 1 Campaign",
        "Contributor 1 Touch Type",
        "Contributor 1 Touch Time",
        "Contributor 2 Partner",
        "Contributor 2 Media Source",
        "Contributor 2 Campaign",
        "Contributor 2 Touch Type",
        "Contributor 2 Touch Time",
        "Contributor 3 Partner",
        "Contributor 3 Media Source",
        "Contributor 3 Campaign",
        "Contributor 3 Touch Type",
        "Contributor 3 Touch Time",
    ]
    user_fields = [
        'Event Revenue Currency',
        'Cost Model',
        'Event Value',
        'App ID',
        'Cost Value',
        'Cost Currency',
        "Attributed Touch Time",
        "Install Time",
        "Event Time",
        "Event Name",
        "Partner",
        "Media Source",
        "Campaign",
        "Adset",
        "Campaign Type",
        "Region",
        "Country Code",
        "State",
        "City",
        "IP",
        "Operator",
        "Carrier",
        "AppsFlyer ID",
        "Customer User ID",
        "Platform",
        "Device Type",
        "OS Version",
        "Device Model",
        "Device Category",
    ]
    af_install_fields = [
        'Event Revenue Currency',
        'Cost Model',
        'Cost Value',
        'Cost Currency',
        'Partner',
        'Campaign Type',
        'Event Time',
        'Event Name',
        'Media Source',
        'Channel',
        'Campaign',
        'Adset',
        'Adset Id',
        'Country Code',
        'State',
        'City',
        'Ip',
        'Operator',
        'Carrier',
        'Appsflyer Id',
        'advertising Id',
        'IDFA',
        'Android Id',
        'IMEI',
        'IDFV',
        'OS Version',
        'Device Model',
        'Device Category',
        'Contributor 1 Partner',
        'Contributor 1 Media Source',
        'Contributor 1 Campaign',
        'Contributor 1 Touch Type',
        'Contributor 1 Touch Time',
        'Contributor 2 Partner',
        'Contributor 2 Media Source',
        'Contributor 2 Campaign',
        'Contributor 2 Touch Type',
        'Contributor 2 Touch Time',
        'Contributor 3 Partner',
        'Contributor 3 Media Source',
        'Contributor 3 Campaign',
        'Contributor 3 Touch Type',
        'Contributor 3 Touch Time'
    ]

class AppsflyerEventTrackingMKT:
    tutorial_login_purchase_fields  = [
        'Install Time',
        'Event Time',
        'Event Name',
        'Event Value',
        'Event Revenue',
        'Event Revenue Currency',
        'Event Source',
        'Media Source',
        'Channel',
        'Campaign',
        'Campaign ID',
        'Adset',
        'Adset ID',
        'Advertising ID',
        'Carrier',
        'Platform',
        'App ID',
        'App Name',
        'Bundle ID',
        'IP',
        'City',
        'Is Retargeting'
    ]
    level_fields = [
        'Install Time',
        'Event Time',
        'Event Name',
        'Event Value',
        'Event Revenue',
        'Event Revenue Currency',
        'Event Source',
        'Media Source',
        'Channel',
        'Campaign',
        'Campaign ID',
        'Adset',
        'Adset ID',
        'Advertising ID',
        'Carrier',
        'Platform',
        'App ID',
        'App Name',
        'Bundle ID',
        'IP',
        'City',
        'Is Retargeting'
    ]

class AggReportFields:
    partners_by_date = [
        'Date',
        'Agency/PMD (af_prt)',
        'Media Source (pid)',
        'Campaign (c)',
        'Impressions',
        'Clicks', 
        'CTR',	
        'Installs',	
        'Conversion Rate',	
        'Sessions',	
        'Loyal Users',
        'Loyal Users/Installs',	
        'Total Revenue',	
        'Total Cost',	
        'ROI',	
        'ARPU',	
        'Average eCPI',
    ]
